### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by aarav123-android** [aarav123-android/order_vegetables#2]
_TODO:_

- [x] Implement 'Create order form' with firebase
- [x] Test out project
- [x] Make Employee App / SMS on doc change
